# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    if: ${{ !startsWith(github.event.commits[0].message, '[rel]') && !startsWith(github.event.commits[0].message, '[ci skip]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: "16.11.1"
      - name: Install dependencies
        run: npm install --prefix ./src
      - name: Devbuild
        run: cd src && npm run dev

  release:
    if: ${{ github.event_name == 'push' && startsWith(github.event.commits[0].message, '[rel]') }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: "16.11.1"
      - name: Build essentials (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install build-essential && sudo apt-get install libxtst-dev libpng++-dev xauth libxss-dev
      - name: Node gyp
        run: npm install -g node-gyp
      - name: Run prebuild script
        run: cd src && node ./scripts/prebuild.js && cd ../
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          package_root: ./src
          github_token: ${{ secrets.github_token }}
          release: true
